### PR TITLE
Added parent_node function

### PR DESCRIPTION
**Pull request by Chimrod**
Merge request for the property mentionned in #10

### CODE REVIEW

**Comment by dbuenzli** [comment]
Thanks ! 

Normally I try to keep the names the way they are in the web APIs modulo uncamlcasification. But the `Brr.El` API is highly remixed, because the DOM api is highly broken. In particular the notion of `node` is not in the vocabulary so I suggest to simply use `parent`. 

Since you have to go over that again could you please put that in a `(** {1:parent Parent} *)` section before the children section and move the function accordingly in the implementation.

**Comment by Chimrod** [comment]
Ok, I'll change that. Do you think I should add an optionnal argument `?⁠only_el:bool` in order to switch between ParentNode or ParentElement ?

**Comment by dbuenzli** [comment]
> Ok, I'll change that. Do you think I should add an optional argument `?⁠only_el:bool` in order to switch between ParentNode or ParentElement ?

Actually the current implementation is not sound. IIUC `parentNode` can return you a document which we should not type as an `El.t`. 
`parentElement` does not do so but doesn't seem to work on text nodes (which for API convenience can hide behind an `El.t`). 

So I think this is what we want:

```ocaml
let parent e = match Jv.find e "parentNode" with 
| None -> None 
| Some e when is_el e -> Some e
| Some _ -> None
```

**Comment by Chimrod** [comment]
Hello, sorry for the delay. (This commit and the PR is the opportunity to send you my greatest whishes for this new year: starting from the health, and a lot of hapiness and creativity).

Let me know if this is ok for you.

Sébastien

**Comment by dbuenzli** [comment]
Thanks for the patch and the wishes  ! A tweaked version of your patch is in as 57523f619f71efa3667da23cc8

**Pull request closed without merging**
